chunk_size: 256
remote_serde: "naive"
remote_url: "fs://host:0/home/share/yuhui-test/test2"
local_cpu: False
max_local_cpu_size: 10
save_unfull_chunk: False
extra_config:
  save_only_first_rank: True
  create_lookup_server_only_on_worker_0_for_mla: True
  save_chunk_meta: False
  use_exists_sync: True
  fs_connector_read_ahead_size: 131072
  fs_connector_relative_tmp_dir: "tmp"
internal_api_server_enabled: True
internal_api_server_port_start: 8080
internal_api_server_include_index_list: [1]
#hit_limit_upper: 0.1
#hit_miss_ratio: 0.9